name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  openjdk21:
    runs-on: ubuntu-latest
    container: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.1_12_1.9.7_3.3.1
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Compile
        run: sbt compile

      - name: Test
        run: sbt test

      - name: Check Formatting
        run: sbt scalafmtCheckAll
